CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Banana - Green', 253.5);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beef - Short Loin', 390.4);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Roe - Flying Fish', 150.54);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Milkettes - 2%', 695.97);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Table Cloth 54x72 Colour', 915.68);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Isomalt', 568.93);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Juice - Pineapple, 48 Oz', 80.6);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Chutney Sauce - Mango', 230.1);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Sauce - Soy Low Sodium - 3.87l', 598.94);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Magnotta, Merlot Sr Vqa', 450.92);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bread Ww Cluster', 223.83);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Remy Pannier Rose', 442.73);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Strawberries - California', 110.54);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Mushroom - Morel Frozen', 636.84);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bread - Petit Baguette', 34.49);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cardamon Seed / Pod', 498.46);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cheese - Comtomme', 500.34);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Calaloo', 956.44);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bread - Italian Roll With Herbs', 996.35);
insert into productos (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Rice - 7 Grain Blend', 25.3);
